### ISSUE TITLE
Collect expertise terms & make a wordCloud

### ISSUE THREAD

**Issue by olgadh** [NBISweden/NBIS-template-outreach#6]

**Comment by verku** [comment]
Done. Might have to change resolution of images again.

**Comment by olgadh** [comment]
This is so cool Verena! @verku.  You've actually done it the bioinformatics way all the way 👍 🥇 . I've just noticed that the term list has "RNAseq" instead of "RNA-seq", "scRNAseq" instead of "scRNA-seq", do you think it would be possible to change to the correct spelling?

**Comment by verku** [comment]
Thanks :-) Yes, of course, that's no problem!

**Comment by verku** [comment]
Done! :-)
